Past Events Update (April 2023)
OWASP/www-chapter-cincinnati pull request #7
Opened 2023-04-30 02:40 UTC by Jeymz

Added April 2023 information and presentation artifact.

closes #6

2023-05-01 13:33 UTC, szh requested changes
Thank you for adding this! Two missing colons, otherwise LGTM!

2023-05-01 13:33 UTC, szh commented on tab_pastevents.md
> +**Speaker Biography** Jay Simmons is a Senior AppSec Analyst for Great American and Security Champion program administrator. He's been working in the AppSec field for over 2 years and was previously
```suggestion
**Speaker Biography:** Jay Simmons is a Senior AppSec Analyst for Great American and Security Champion program administrator. He's been working in the AppSec field for over 2 years and was previously a developer.
```

2023-05-01 13:33 UTC, szh commented on tab_pastevents.md
> +**Presentation**
```suggestion
**Presentation:**
```

2023-05-01 22:42 UTC, Jeymz commented
> Thank you for adding this! Two missing colons, otherwise LGTM!

Committed to request. Should be good to go now.

2023-05-02 13:26 UTC, szh approved these changes
LGTM

2023-05-02 13:26 UTC, merged